### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by TheNoxx** [TwoBeers/shiword#48]
Hi,

Rss feed won't disable
I did disable it trough Theme options -> navigation buttons
Can you help me?
TheNoxx
![thme options shiword](https://cloud.githubusercontent.com/assets/7497699/2927961/a816097e-d775-11e3-8292-2341ea868f3f.jpg)

**Comment by jimo** [comment]
Hi,
It's strange, because I tried it in our testing enviroment and everything works fine.
Maybe you mean the rss icon in the upper right corner?
![swrss](https://cloud.githubusercontent.com/assets/454482/2954483/011e65ac-da73-11e3-8990-180570d5ebb9.jpg)
In this case, you have to edit the code:
- open functions.php with the editor
- delete lines (1127->1131)

```
    <div id="rss_imglink" class="minibutton">
        <a href="<?php echo esc_url( apply_filters( 'shiword_filter_rss_service', get_bloginfo( 'rss2_url' ) ) ); ?>" title="<?php esc_attr_e( 'Syndicate this site using RSS 2.0', 'shiword' ); ?>">
            <span class="minib_img">&nbsp;</span>
        </a>
    </div>
```

Jimo

**Comment by TheNoxx** [comment]
L.S.

Yes i did mean the rrs icon in the upper right corner!
Thank you for your support.

Regards,
TheNoxx
The Netherlands

Verstuurd vanaf mijn iPad Air (7.04 jailbreak Evasi0n)
